"""
Django settings for DerbyDay project.

Generated by 'django-admin startproject' using Django 2.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
#from dotenv import load_dotenv ##requires pip install python-dotenv

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Development settings: See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/
# SECURITY WARNING: keep the secret key used in production secret!

#### Consider replacing secret .env file with AWS Parameter Store / KMS:
## https://engineering.instawork.com/django-settings-in-the-cloud-aa3fc547a2b4

##Can automate loading .env file with python-dotenv.load_dotenv()
## https://www.youtube.com/watch?v=2uaTPmNvH0I

if 'DJANGO_DEBUG_FALSE' in os.environ:
    DEBUG = False
    SECRET_KEY = os.environ['DJANGO_SECRET_KEY']
    ALLOWED_HOSTS = os.environ['SITENAME']
else:
    DEBUG = True
    SECRET_KEY = 'insecure-key-for-dev'
    ALLOWED_HOSTS = []

#### Example secrets.sh file:
## Consider replacing this file with AWS Parameter Store / KMS:
## https://engineering.instawork.com/django-settings-in-the-cloud-aa3fc547a2b4

#export DJANGO_SECRET_KEY='secure-key-for-prod'
#export ALLOWED_HOSTS="['localhost', '127.0.0.1', 'xxx.xxx.xxx.xxx', 'domain.com']"
#export PATH_TO_MYSQL_CNF='mysql.cnf' ## See example mysql.cnf after DATABASES{} below.
##export DJANGO_DEBUG_FALSE=TRUE # uncomment to set true for production

# Must use 'source ./secrets.sh'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'DerbyDayApp.apps.DerbydayappConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'DerbyDay.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'DerbyDay.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'OPTIONS': {
            'read_default_file': os.path.join(BASE_DIR, os.environ['PATH_TO_MYSQL_CNF']), #Use secrets.sh to provide path to a MySQL Options File
            # https://docs.djangoproject.com/en/1.7/ref/databases/#connecting-to-the-database
        },
    }
}
##MySQL Options File Example (replace with actual values):
# [client]
# database = DB_NAME
# host = 127.0.0.1 # "localhost" does not work sometimes
# user = DB_USER
# password = DB_PASSWORD #cat ./bitnami_credentials for root passwd
# default-character-set = utf8mb4
# socket=/var/lib/mysql/mysql.sock

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
